name: Build and Test WireMock

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-wiremock:latest .

      - name: Test WireMock Endpoint
        run: |
          docker run -d --rm -p 8080:8080 --name wiremock-test my-wiremock:latest
          sleep 5
          curl -f http://localhost:8080/test-api | grep 'Działa testowy endpoint!'
